### ISSUE TITLE
solar panels getting 0 energy

### ISSUE THREAD

**Issue by jon-y** [Sigma88/Galactic-Neighborhood#10] opened 2015-09-24 23:01 UTC
It does show expected exposure values but no energy is produced. Removing this mod restores the solar panel behavior.

Anything in the logs I should be looking for? I am using KSP Interstellar.

**Comment by Sigma88** [comment] 2015-09-25 11:45
If you are using hyperedit to get in orbit around a star, could you try to: 

1- quick save
2- go back to the KSC
3- go to the tracking station
4- go to the craft

I think it may be related to this issue

https://github.com/Kopernicus/Kopernicus/issues/90

(when going to the craft directly from the tracking station, solar panels should work)

the code for electric charge generation is not 100% done, so you may have weird values

were is your ship?

**Comment by jon-y** [comment] 2015-09-25 13:26
Will try that. The ship in question is a lander on Mun with solar panels.

Edit: Speaking of quicksave/quickload, I did do that when attempting to land on Mun, but also notice the same issue on other ships, eg one orbiting Kerbin when using the tracking station to fly it.

Edit 2: Tried the quicksave and jumping to the craft from tracking station way, still getting 0 ECs.

**Comment by Sigma88** [comment] 2015-09-25 23:24
you're right, I can see the same thing.

It wasn't behaving like this when I released 0.0.4 so I guess it may be something in kopernicus.

I cannot be 100% sure, I will need some time to test :)

thanks for reporting

**Comment by Sigma88** [comment] 2015-10-02 00:43
after further testing, the issue is the same as https://github.com/Kopernicus/Kopernicus/issues/90.

if you change star it will display the correct values as long as you don't save/reload

**Comment by jon-y** [comment] 2015-10-02 10:40
Oh well, I don't mind using hyperedit to bump the energy levels since there is no escaping it, I don't think I have the infrastructure in place to reach another star yet :)

**Comment by Sigma88** [comment] 2015-10-02 12:11
btw, this is not intended. It's a bug and it's being worked on :)

**Comment by Olympic1** [comment] 2015-10-26 10:04
This should be fixed in KSP 1.0.5

Don't quote me on that

**Comment by Sigma88** [comment] 2015-10-28 09:37
https://github.com/Kopernicus/Kopernicus/issues/90

damn you thomas! :)

**Comment by Sigma88** [comment] 2015-10-29 11:37
this is totally thomas' fault

**Comment by jon-y** [comment] 2015-10-29 22:47
What just happened?

**Comment by Sigma88** [comment] 2015-10-29 23:13
nothing, I was trying the IRC link for this repository :)

**Comment by Sigma88** [comment] 2016-04-24 19:11
so, kopernicus solved the Ec generation bug, but that brought up another bug that makes ships explode when switching star. I had to stop the stars in GN from generating Ec sadly.
there is nothing I can do to solve this issue, so I have put a workaround in GN (solar panels now can produce Ec like RTGs.

**Closed as completed by Sigma88** 2016-04-24 19:11 UTC
